### ISSUE TITLE
[0.1.1] pecl archive is broken

### ISSUE THREAD

**Issue by remicollet** [ace411/php-trie-ext#6]
This is obviously not an archive properly created using the "pecl package" command

```
$ tar tf php_trie-0.1.1.tgz
LICENSE
common.cpp
...
```

Expected
```
package.xml
php_trie-0.1.1/LICENSE
php_trie-0.1.1/README.md
php_trie-0.1.1/config.m4

```

**Comment by remicollet** [comment]
Also missing checksum in package.xml

`   <file name="LICENSE" role="doc" />`

instead of 

`   <file md5sum="b6f51bda02a297a3bb34b547639abb4e" name="LICENSE" role="doc" />`

**Comment by remicollet** [comment]
Also archive is not compressed

```
$ file php_trie-0.1.1.tgz
php_trie-0.1.1.tgz: POSIX tar archive (GNU)
```

instead of

`php_trie-0.1.1.tgz: gzip compressed data, max compression, from Unix, original size modulo 2^32 129024`

**Comment by ace411** [comment]
All right. Can I re-upload v0.1.1 with all the prescribed fixes?

**Comment by remicollet** [comment]
> All right. Can I re-upload v0.1.1 with all the prescribed fixes?

This is possible, but usually considered as a bad practice
Better to create a 0.1.2

**Comment by ace411** [comment]
Thanks. See https://github.com/ace411/php-trie-ext/pull/8

**Comment by remicollet** [comment]
BTW, I don't see 0.1.2 on pecl ?

**Comment by ace411** [comment]
Just uploaded it. Thanks for the reminder.

**Comment by remicollet** [comment]
Forget, just appeared
